### ISSUE TITLE
Plus and minus buttons are bugged

### ISSUE THREAD

**Issue by nschoenwald** [mclemente/fvtt-dice-tray#1]
Pressing the plus and minus buttons keeps attaching new modifiers to the roll instead of changing the existing one.

<img width="300" alt="image" src="https://github.com/mclemente/fvtt-dice-tray/assets/72390280/8cf12a6b-50dd-4de3-8ba3-372314d92c49">

**Comment by mclemente** [comment]
Should be fixed now.
