### ISSUE TITLE
Savage Worlds: the WILD button behaves incorrectly when clicking a dice button multiple times.

### ISSUE THREAD

**Issue by CyrilRonseaux** [mclemente/fvtt-dice-tray#13]
Steps:
* Click Wild
![image](https://github.com/mclemente/fvtt-dice-tray/assets/38113746/19e4a350-4c77-47c8-915d-8dc971550fb4)

* then d4, once (formula is perfect)
![image](https://github.com/mclemente/fvtt-dice-tray/assets/38113746/22a0af9a-99b4-4dbf-9150-130c19f47744)

* then d4 again
![image](https://github.com/mclemente/fvtt-dice-tray/assets/38113746/35754baa-6f55-4870-a170-8b2943e6e3c3)

the resulting formule shouldn't be /r `{2d4x=,1d6x=}kh` but `/r {1d4x=,1d4x=,1d6x=}kh2` (roll 2 separate d4 skill die along the d6 wild die, then keep and display only the two highest).

For non-wild rolls, there is no way to know whether the player/master, wants to roll separate skill dice or add them up (e.g. for damage). To me, adding non-wild rolls together to be the most common use case, so I would keep the existing behavior (going with `2d4x=`). So only the behavior when Wild is selected should change.

**Comment by kristianserrano** [comment]
I think for SWADE, this might call for another state button for Trait roll. If Trait is enabled, clicking multiple dice adds to the pool instead of increasing the number of dice for that specific die type.

**Comment by mclemente** [comment]
> I think for SWADE, this might call for another state button for Trait roll. If Trait is enabled, clicking multiple dice adds to the pool instead of increasing the number of dice for that specific die type.

I tried adding a new button as you suggested, but it is too cramped to fit a new one, be it grouped with the other 2 or adding a new section.

Instead, I've added a new setting that changes the button to the requested behavior. I wasn't sure how to name it, so I went with "Use Dice Pool for Wild Button".
