### ISSUE TITLE
Extra buttons (fortune/misfortune) not rendering in PF2e v5.11+

### ISSUE THREAD

**Issue by tdhsmith** [mclemente/fvtt-dice-tray#14]
A change in the global CSS in the PF2e system causes the `hidden` attribute to have style `display: none !important`, which  jQuery's [show() function](https://api.jquery.com/show/) won't override.

I filed a pretty long bug report there (https://github.com/foundryvtt/pf2e/issues/12869), but IMO it's not really an incorrect approach on their end and would probably take a lot of effort to "fix".

Comparatively I'd suggest that this module could change approach slightly, for example just a one line swap in [TemplateDiceMap._createExtraButtons](https://github.com/mclemente/fvtt-dice-tray/blob/599383774ab710083071bd9ac6950cef5317f174/src/module/maps/templates/template.js#L118) to:
```js
html.find("#dice-tray-math").removeAttr("hidden");
```
...would be sufficient to make them render again.

**Comment by mclemente** [comment]
I've applied your suggestion. Thank you
