### ISSUE TITLE
Dice Tray disappeared

### ISSUE THREAD

**Issue by revwez** [mclemente/fvtt-dice-tray#2]
Hi,

I ran the update to dice tray 2.0 (foundry V11, on The Forge, running the Basic Fantasy system) and when I started the game, the tray was gone (chat looks as if it wasn't installed). The module is enabled and the tray is enabled in settings. I downgraded and it came back. If they is anything I can do to help troubleshoot, please let me know!

**Comment by asacolips** [comment]
@revwez there was a bug related to the dice tray not appearing on systems that didn't have their own custom dice tray defined, but that should be working as of the 2.0.3 version. Try upgrading and again and let us know if it works 🙂

**Comment by revwez** [comment]
Cool. I will.Sent from my iPadOn Oct 26, 2023, at 10:18 PM, Matt Smith ***@***.***> wrote:﻿
@revwez there was a bug related to the dice tray not appearing on systems that didn't have their own custom dice tray defined, but that should be working as of the 2.0.3 version. Try upgrading and again and let us know if it works 🙂

**Comment by revwez** [comment]
Just checked… all is good now! Thanks!
