### ISSUE TITLE
2.1.12: Dice Tray Gone

### ISSUE THREAD

**Issue by mageofthesands** [mclemente/fvtt-dice-tray#22]
Dice Tray 2.1.12.  Foundry version 11.  Build 315.  Pathfinder 1e 10.4.  One module active: Dice Tray.
The tray is not there.  Dev console gives no warnings.

**Comment by ronin-seven** [comment]
see https://github.com/mclemente/fvtt-dice-tray/issues/20 for the root cause.

in the meantime, you can install the previous version using this manifest url: https://github.com/mclemente/fvtt-dice-tray/releases/download/2.1.11/module.json

**Comment by mclemente** [comment]
Sorry, I forgot the module was still V11-compatible when I've made the release and immediately left for a family trip over the weekend, so I could only get to it now.
The [2.1.12.1 release](https://github.com/mclemente/fvtt-dice-tray/releases/tag/2.1.12.1) should fix this.
