### ISSUE TITLE
Tray disappeared

### ISSUE THREAD

**Issue by lizzard77** [mclemente/fvtt-dice-tray#27]
Using Foundry v11.315, 5e v2.4.1. 

Had Dice Tray in my world from the start. About two weeks ago, maybe after an update of the modules, the dice tray icons disappeared. There are no errors in the browser console. The problem occurs in both my regular game world and in a fresh, empty world without any other modules. 

Any help is appreciated, let me know if you need more info or tests!

**Comment by mclemente** [comment]
Are you on version 2.1.12? Then reinstall the module.

**Comment by lizzard77** [comment]
I am - and that fixed it, thanks for the instant support!

**Comment by lizzard77** [comment]
Fixed!
